name: TEST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive


      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'


      - name: run the whole pipeline
        run: cd geneIDs && bash main_geneIDs.sh


      - uses: actions/upload-artifact@v2
        with:
          path: ./
